apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  labels:
    app.kubernetes.io/name: ajp-api
    app.kubernetes.io/component: api-external
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 31481
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ajp-api
