apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:9.21
          args:
            - -url=jdbc:postgresql://postgres:5432/ajp_db
            - -user=postgres
            - -password=postgres
            - migrate
          volumeMounts:
            - name: migrations-volume
              mountPath: /flyway/sql
      volumes:
        - name: migrations-volume
          persistentVolumeClaim:
            claimName: flyway-migrations-pvc
      restartPolicy: OnFailure
